### ISSUE TITLE
this.props.onValueChange is not a function

### ISSUE THREAD

**Issue by leeeomaaax** [netbeast/react-native-dial#1]
this.props.onValueChange is not a function. (In 'this.props.onValueChange(deg,radius)', 'this.props.onValueChange' is undefined)

Did you manage to make this component work?

**Comment by jsdario** [comment]
Yes – we are using it on production, see https://getyeti.co.

Sorry the code is not yet documented, you need to pass the component  a function to listen to angle or scale updates.

```
<Dial onValueChange={function (deg, radius) {
  console.log({deg, radius})
}) />
```

I'll try to document it ASAP. Meanwhile, you'll need to read the code a little bit to see which props are mandatory.

**Comment by leeeomaaax** [comment]
@jsdario Thank you!

**Comment by jsdario** [comment]
@leeeomaaax check if the latest commits adds any valuable information https://github.com/netbeast/react-native-dial/commit/19a86a4e1c97f6ff2eb16a8d094ac3032be9a67f if it solved your case, please be so kind to close this issue 🚫 .

If you find this project useful please donate us a ⭐️ .
If you need anything else, you are welcome to open a new issue :)
