### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by grifotv** [netbeast/react-native-dial#4]
Great work guys.

Would you have an example of implementation to share? I saw in the root README this:

```
initialRadius={brightness * DIF_RADIUS / 100 + MIN_RADIUS}
radiusMax={MAX_RADIUS}
radiusMin={MIN_RADIUS}
```
but was wondering what would be `brightness`, `DIF_RADIUS`, `MIN_RADIUS` or `MAX_RADIUS`.

Thanks!

**Comment by jsdario** [comment]
Good question, they are just there for the example. They are unit-based proportions so basically percentages expressed as units. In our codebase:

```
const MAX_RADIUS = 1.15
const MIN_RADIUS = 0.75
const DIF_RADIUS = 0.4 // just max - min
```

On its max radius the Dial will be 115% its original size, its min radius is going to be 75% of the size, the diff is just a constant and brightness is a percentage as we are used to (e.g. 60)

I understand it can be a little bit opaque, I encourage you to change those values n a PR for a better text

**Comment by grifotv** [comment]
thanks!
