### ISSUE TITLE
ColorWheel ?

### ISSUE THREAD

**Issue by FrankDoersam** [netbeast/react-native-dial#8]
Hello, thank you for the top project. In the example ColorWheel is used, unfortunately I can not find this in the project? Is this the ColorWheel that the Yeti App uses?

Many Thanks.

**Comment by jsdario** [comment]
I quickly checked the repo and can't find the reference to `ColorWheel`. Could you specify a little bit more? Do you need the image or are you looking for a missing component? Is it a bug?

**Comment by FrankDoersam** [comment]
Thank you for the fast answer. Exactly the project I meant (y) :). Is the ColorWhell of Yeti also available on github right?

**Comment by jsdario** [comment]
This is the exact project used at Yeti, indeed, you can check it here: https://github.com/netbeast/react-native-color-wheel

![color-wheel](https://user-images.githubusercontent.com/5166506/34570404-fb8ea1e2-f16b-11e7-9c3d-421c89cfda2f.png)

**Comment by FrankDoersam** [comment]
Thank you very much the app is really awesome! I am currently teaching React Native something. What's the name of a control, how the app uses it in Discovery?

**Comment by jsdario** [comment]
That is a very side topic, so I'll close the issue for now. If you are interested on learning more, check this other repo and join the slack channel https://github.com/netbeast/bigfoot :)

Thanks a lot for your kind comments and opening the issue!
